ТЗ№13: добавлены контроллеры для User и Item
ReTeRWert/java-shareit pull request #1
Opened 2023-05-01 08:07 UTC by ReTeRWert

2023-05-02 08:20 UTC, TomattmanYandex requested changes
Привет, коменты как обычно в коде
к части про пользователей не добавлял коменты там то же самое что и с итемами
отдельный комент про пакеты
В текущем подходе разбиения по пакетам, обычно делают пакет под конкретную сущность например итемы а уже в нем не делают дополнительного разбиения по пакетом просто в пакете item все классы относящиеся к нему

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/Status.java
> +package ru.practicum.shareit;
статус относится к букингу, лучше закинуть к нему в пакет

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Item addItem(@RequestHeader("X-Sharer-User-Id") Long userId,
на уровне контроллеров работаем с DTO т.е. и принимаем их и возвращаем их

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull
стоит добавить больше полей в DTO например нам нужен id чтобы потом иметь возвожность работать с этим итемом по id

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ItemRequest request;
Почему все поля кроме этого - final

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +    public Item addItem(Long userId, ItemDto item) {
Преобразование DTO в обьект и обратно обычно происходит на уровне сервиса. 
уровень хранилища работаетт только с самим обьектом
уровень сервиса работает с обьектами дто и хранилищами
урвоень контроллера работает с dto и сервисами

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +                    .build();
может стоило не делать все переменные финальнми, чтобы тут было меньше мороки и просто сеттерами знгачения проставить?

2023-05-02 08:20 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User getUser(@PathVariable Long userId) {
аналогично про то, что в контроллере используем DTO

2023-05-02 09:58 UTC, ReTeRWert commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private ItemRequest request;
если пометить final, его надо будет создавать в ItemMapper, а сейчас функционала по сути нет, поэтому я решил пока так оставить.

2023-05-02 09:58 UTC, ReTeRWert commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorageImpl.java
> +                    .build();
я просто хотел попробовать делать через билдер

2023-05-03 09:13 UTC, TomattmanYandex requested changes
Все еще надо поправить

2023-05-03 09:13 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/InMemoryItemStorageImpl.java
> +    public Item addItem(Long userId, ItemDto item) {
на уровне хранилища мы работает с обьектом который хранится в хранилище, следовательно во входных параметрах мы принимает сам обьект, а преобразование из дто в обьект надо сделать на уровне сервиса

2023-05-03 09:13 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                itemStorage.updateItem(userId, itemId, item));
на урвоень хранилища передаем не дто а уже смапленный обьект

2023-05-03 09:13 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/InMemoryUserStorageImpl.java
> +    public User addUser(UserDto user) {
в параметрах принимаем не дто а сам обьект

2023-05-03 09:13 UTC, TomattmanYandex commented on src/main/java/ru/practicum/shareit/user/UserMapper.java
> +    public static User toUser(Long userId, UserDto user) {
зачем отдельным параметром id ведь он есть в обьекте

2023-05-04 13:25 UTC, TomattmanYandex approved these changes
ПРинято

2023-05-04 15:14 UTC, merged